// <auto-generated />
namespace BolsaDeTrabajo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FormacionCambioPeriodos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FormacionCambioPeriodos));
        
        string IMigrationMetadata.Id
        {
            get { return "201709271840159_FormacionCambioPeriodos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
