namespace BolsaDeTrabajo.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddCatalogosPaises : DbMigration
    {
        public override void Up()
        {
            Sql("SET IDENTITY_INSERT [Sist].[Paises] ON");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (1, 'Australia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (2, 'Austria')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (3, 'Azerbaiya')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (4, 'Anguilla')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (5, 'Argentina')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (6, 'Armenia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (7, 'Bielorrusia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (8, 'Belice')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (9, 'Belgica')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (10, 'Bermudas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (11, 'Bulgaria')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (12, 'Brasil')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (13, 'Reino Unido')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (14, 'Hungria')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (15, 'Vietnam')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (16, 'Haiti')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (17, 'Guadalupe')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (18, 'Alemania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (19, 'Paises Bajos, Holanda')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (20, 'Grecia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (21, 'Georgia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (22, 'Dinamarca')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (23, 'Egipto')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (24, 'Israel')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (25, 'India')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (26, 'Ira')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (27, 'Irlanda')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (28, 'España')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (29, 'Italia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (30, 'Kazajsta')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (31, 'Cameru')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (32, 'Canada')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (33, 'Chipre')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (34, 'Kirguista')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (35, 'China')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (36, 'Costa Rica')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (37, 'Kuwait')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (38, 'Letonia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (39, 'Libia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (40, 'Lituania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (41, 'Luxemburgo')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (42, 'Mexico')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (43, 'Moldavia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (44, 'Monaco')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (45, 'Nueva Zelanda')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (46, 'Noruega')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (47, 'Polonia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (48, 'Portugal')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (49, 'Reunio')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (50, 'Rusia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (51, 'El Salvador')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (52, 'Eslovaquia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (53, 'Eslovenia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (54, 'Surinam')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (55, 'Estados Unidos')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (56, 'Tadjikista')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (57, 'Turkmenista')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (58, 'Islas Turcas y Caicos')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (59, 'Turquia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (60, 'Uganda')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (61, 'Uzbekista')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (62, 'Ucrania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (63, 'Finlandia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (64, 'Francia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (65, 'Republica Checa')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (66, 'Suiza')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (67, 'Suecia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (68, 'Estonia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (69, 'Corea del Sur')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (70, 'Japo')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (71, 'Croacia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (72, 'Rumania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (73, 'Hong Kong')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (74, 'Indonesia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (75, 'Jordania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (76, 'Malasia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (77, 'Singapur')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (78, 'Taiwa')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (79, 'Bosnia y Herzegovina')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (80, 'Bahamas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (81, 'Chile')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (82, 'Colombia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (83, 'Islandia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (84, 'Corea del Norte')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (85, 'Macedonia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (86, 'Malta')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (87, 'Pakista')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (88, 'Papua-Nueva Guinea')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (89, 'Peru')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (90, 'Filipinas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (91, 'Arabia Saudita')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (92, 'Tailandia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (93, 'Emiratos arabes Unidos')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (94, 'Groenlandia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (95, 'Venezuela')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (96, 'Zimbabwe')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (97, 'Kenia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (98, 'Algeria')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (99, 'Libano')");
            
Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (100, 'Botsuana')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (101, 'Tanzania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (102, 'Namibia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (103, 'Ecuador')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (104, 'Marruecos')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (105, 'Ghana')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (106, 'Siria')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (107, 'Nepal')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (108, 'Mauritania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (109, 'Seychelles')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (110, 'Paraguay')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (111, 'Uruguay')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (112, 'Congo (Brazzaville)')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (113, 'Cuba')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (114, 'Albania')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (115, 'Nigeria')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (116, 'Zambia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (117, 'Mozambique')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (118, 'Angola')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (119, 'Sri Lanka')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (120, 'Etiopia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (121, 'Tunez')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (122, 'Bolivia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (123, 'Panama')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (124, 'Malawi')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (125, 'Liechtenstei')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (126, 'Bahrei')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (127, 'Barbados')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (128, 'Chad')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (129, 'Man, Isla de')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (130, 'Jamaica')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (131, 'Mali')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (132, 'Madagascar')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (133, 'Senegal')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (134, 'Togo')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (135, 'Honduras')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (136, 'Republica Dominicana')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (137, 'Mongolia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (138, 'Irak')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (139, 'Sudafrica')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (140, 'Aruba')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (141, 'Gibraltar')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (142, 'Afganista')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (143, 'Andorra')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (144, 'Antigua y Barbuda')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (145, 'Bangladesh')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (146, 'Beni')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (147, 'Buta')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (148, 'Islas Virgenes Britanicas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (149, 'Brunei')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (150, 'Burkina Faso')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (151, 'Burundi')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (152, 'Camboya')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (153, 'Cabo Verde')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (154, 'Comores')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (155, 'Congo (Kinshasa)')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (156, 'Cook, Islas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (157, 'Costa de Marfil')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (158, 'Djibouti, Yibuti')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (159, 'Timor Oriental')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (160, 'Guinea Ecuatorial')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (161, 'Eritrea')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (162, 'Feroe, Islas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (163, 'Fiyi')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (164, 'Polinesia Francesa')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (165, 'Gabo')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (166, 'Gambia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (167, 'Granada')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (168, 'Guatemala')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (169, 'Guernsey')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (170, 'Guinea')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (171, 'Guinea-Bissau')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (172, 'Guyana')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (173, 'Jersey')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (174, 'Kiribati')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (175, 'Laos')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (176, 'Lesotho')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (177, 'Liberia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (178, 'Maldivas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (179, 'Martinica')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (180, 'Mauricio')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (181, 'Myanmar')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (182, 'Nauru')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (183, 'Antillas Holandesas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (184, 'Nueva Caledonia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (185, 'Nicaragua')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (186, 'Niger')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (187, 'Norfolk Island')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (188, 'Oma')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (189, 'Isla Pitcair')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (190, 'Qatar')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (191, 'Ruanda')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (192, 'Santa Elena')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (193, 'San Cristobal y Nevis')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (194, 'Santa Lucia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (195, 'San Pedro y Miquelo')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (196, 'San Vincente y Granadinas')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (197, 'Samoa')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (198, 'San Marino')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (199, 'San Tome y Principe')");
            
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (200, 'Serbia y Montenegro')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (201, 'Sierra Leona')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (202, 'Islas Salomo')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (203, 'Somalia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (204, 'Suda')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (205, 'Swazilandia')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (206, 'Tokelau')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (207, 'Tonga')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (208, 'Trinidad y Tobago')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (209, 'Tuvalu')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (210, 'Vanuatu')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (211, 'Wallis y Futuna')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (212, 'Sahara Occidental')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (213, 'Yeme')");
            Sql("INSERT [sist].[Paises] ([Id], [pais]) VALUES (214, 'Puerto Rico')");
        }
        
        public override void Down()
        {
        }
    }
}
