// <auto-generated />
namespace BolsaDeTrabajo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration007 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration007));
        
        string IMigrationMetadata.Id
        {
            get { return "201709011739278_migration.0.07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
