namespace BolsaDeTrabajo.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class carreras : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Acupuntura y medicina oriental')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración / administrador de redes y sistemas ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración / gestión de servicios sanitarios')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración /administrador de sistemas, redes y comunicaciones LAN/WAN')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración /gestión de servicios de hostelería')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración /gestión hotelera')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración de sistemas informáticos en red ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración publica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración y gestión de empresas, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Administración/gestión de servicios de hostelería')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Alimentación, nutrición y bienestar, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Animación, tecnología interactiva, gráficos en video y efectos especiales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Antropología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Aprendizaje de una lengua extranjera')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Arquitectura')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Arquitectura naval e ingeniería marítima')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Arte dramático/teatro, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Arte/estudios artísticos, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Artes liberales y ciencias/estudios liberales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Artes plásticas, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Asesoramiento psicológico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Audiología y trastornos del habla y del lenguaje')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Banca y servicios financieros')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biblioteconomía')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biblioteconomía y documentación ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Bienes inmuebles')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Bioinformática')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Bioingeniería e ingeniería biomédica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biología humana')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biología marina y oceanografía biológica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biología molecular')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biología, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biología/ciencias biológicas, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Bioquímica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Bioquímica y biología molecular')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Biotecnología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Botánica / biología vegetal')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencia de materiales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencia y gestión de la fauna, las especies marinas y los espacios naturales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias biomédicas, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias de la gestión ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias de la nutrición')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias físicas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias físicas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias medioambientales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias naturales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias políticas y gobierno')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias sociales ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias vegetales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias veterinarias / ciencias clínicas veterinarias, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ciencias y trastornos de la comunicación, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Cine y video')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Cinematografía y producción de cine y video')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Comercialización ene le ámbito de la moda')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Comunicación empresarial')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Comunicación oral y retorica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Comunicación organizacional, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Conservación de jardines y céspedes deportivos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Contabilidad')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Contabilidad y finanzas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Contabilidad y gestión empresarial ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Derecho')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Derecho financiero y tributario')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Derecho internacional y estudios juridico internacionales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Derecho/jurisprudencia canadiense')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Derecho/jurisprudencia estadounidense ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Desarrollo de aplicaciones web')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Desarrollo de páginas web, contenido digital /multimedia y recursos informáticos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Desarrollo de recursos humanos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Desarrollo humano y familia, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Desarrollo, planificación y gestión de uso de suelo')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Dirección y administración en el sector educativo, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Diseño de interiores')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Diseño de moda')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Diseño de videojuegos y contenido interactivo')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Diseño grafico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Diseño industrial y de productos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Diseño y artes aplicadas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Diseño y comunicación visual, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Economía')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Economía de la empresa')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Educación primaria')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Educación universitaria/gestión en el ámbito de la educación universitaria')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Empresa, gestión, marketing y disciplinas afines')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Empresa/comercio, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Enfermería')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Enfermería de urgencias y emergencias')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Enseñanzas artísticas y artes visuales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Escritura y redacción, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estadística')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios bíblicos/estudios de la biblia')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios de España y Portugal')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios de la zona del pacifico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios de los medios de comunicación ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios franceses')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios generales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios japoneses')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios judaicos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios judíos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios jurídicos, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios jurídicos, nivel universitario')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios jurídicos, nivel universitario')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios norteamericanos/civilización norteamericana')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios pastorales /orientación pastoral')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios rusos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios rusos, de Europa central, de Europa del este y de Eurasia')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios sobre comunicación y medios')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios sobre el territorio urbano')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios sobre naturaleza, ocio y tiempo libre ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios sobre políticas de seguridad nacional')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios ucranianos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios uraloaltaicos y del centro asiático')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios zonales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Estudios zonales, étnicos, culturales y de grupos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Farmacia')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Farmacología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Filosofía')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Finanzas, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Física')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Física nuclear')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Física química')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Física teórica y matemática')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Fisioterapia/fisioterapeuta')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Fotografía')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Geografía')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Geología/ciencias de la tierra, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de centros universitarios técnicos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de empresas/organizaciones sin ánimo de lucro/entidades publicas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de la construcción')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de los recursos naturales y políticas afines')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de proyectos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de proyectos de tecnología de la información')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de recursos de la información')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de recursos humanos/administración de personal, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de servicios turísticos y de viaje')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión de situaciones de crisis /urgencias / desastre')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión del agua, las zonas húmedas y los recursos marinos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión forestal en el medio urbano')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión industrial/de ingeniería')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión logística, de materiales y de la cadena de suministros')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión y servicios de recursos humanos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión y supervisión de oficinas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Gestión y supervisión de operaciones')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Hidrología y gestión de recursos hídricos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Higienista dental')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Historia')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Historia de los estados unidos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Historia del arte, crítica de arte y conservación del patrimonio artístico.')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Historia y arqueología del mundo clásico, mediterráneo antiguo y oriente próximo')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Humanidades/estudios humanísticos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Informática, comunicaciones y servicios de asistencia')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería aeroespacial, aeronáutica y astronáutica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería agrónoma y producción vegetal')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería biomédica/medica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería civil')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería de materiales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería de software')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería de telecomunicaciones')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería eléctrica y electrónica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería eléctrica, electrónica y de comunicaciones ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería física')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería física/física aplicada')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería industrial')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería informática')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería mecánica ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería medioambiental / ingeniería de salud medioambiental')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería nuclear')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería química')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ingeniería química y biomolecular')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Interacción entre el ser humano y la tecnología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Inversiones y títulos valores')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Investigación de operaciones /operativa')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Jazz/estudios de jazz')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Justicia penal y servicios correccionales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Justicia penal/gestión de la aplicación de la ley')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Justicia penal/Policía')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Justicia penal/seguridad')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Kinesiología/quinesiología y ciencia del ejercicio')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Kinesioterapia/kinesioterapeuta')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Lengua y literatura inglesa')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Lengua y literatura inglesa, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Lengua y literatura japonesa')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Lengua y literatura ucraniana')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Lengua y literatura urdu')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Liderazgo empresarial')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Lingüística')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Literatura infantil y juvenil')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Literatura inglesa (británica)')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Marketing')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Marketing / gestión de marketing, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Matemáticas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Matemáticas aplicadas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Matemáticas e informática')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Mecánica y reparación, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Medicina')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Medicina naturista/medicina natural/naturopatía')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Medicina quiropráctica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Microbiología, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Música')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Náutica/ingeniería marítima')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Negocios internacionales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Negocios internacionales /comercio internacional')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Neurobiología y conducta')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Neurociencia')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Nutrición humana')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Oceanografía, química y física')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Odontología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Operaciones y ciencias militares')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Óptica y optometría')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Optometría')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ordenación del territorio, urbanismo y medio ambiente')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Orientación /orientación de rehabilitación profesional')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Orientación de alumnos de primaria y secundaria')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Orientación de alumnos universitario')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Orientación pastoral para la juventud')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Orientación pastoral para la vida urbana')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Patología vegetal / fitopatología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Pedagogía waldorf')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Periodismo')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Planificación urbana y regional')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Planificación y servicios financieros')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Política y gobierno de estados unidos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Preservación y conservación del patrimonio histórico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Procuraduría')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Profesiones y estudios jurídicos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Programación informática')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Programación informática, aplicaciones especificas')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Psicología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Psicología clínica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Psicología del trabajo')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Publicidad')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química ambiental')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química analítica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química aplicada a la ingeniería')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química de materiales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química de polímeros')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química física')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química inorgánica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química medica y farmacéutica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Química orgánica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Radio y televisión')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Recursos naturales/conservación, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Relaciones internacionales y asuntos exteriores')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Relaciones laborales industriales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Relaciones publicas /gestión de imagen')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Religión / estudios religiosos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Residencia en medicina de urgencias')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Residencia en medicina zoológica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Retórica y composición')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Salud y bienestar, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Salud y educación física')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Secretariado judicial')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Servicios financieros y gestión financiera')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Servicios humanos, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Servicios sanitarios / ciencias de la salud, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Sistema tributario')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Sistemas de información de gestión, general')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Sociología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Teatro')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Técnico de laboratorio clínico/medico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Técnico en salud animal / auxiliar de veterinaria')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Técnico quirúrgico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología / técnico de ingeniería eléctrica, electrónica y de comunicaciones')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología / técnico de ingeniería química ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología / técnico industrial')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología de la educación')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología de la información ')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología de procesos químicos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología en la educación')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología informática / tecnología de sistemas informáticos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnología química / Técnico químico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Tecnologías relacionadas con la ingeniería mecánica')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Teología/estudios teológicos')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Terapia mediante masaje / masaje terapéutico')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Terapia ocupacional')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Trabajo social')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Transcripción de juicios/taquigrafía judicial')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Trastornos del habla y del lenguaje')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ventas especializadas, promoción comercial y actividades de marketing')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Ventas generales, promoción comercial y actividades de marketing afines')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Veterinaria')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Viajes y exploración')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Virología')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Voz y opera')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Zoo terapia / terapia asistida con animales')");
            Sql("INSERT INTO [Sist].[Carreras] VALUES('Zoología /biología animal')");

        }

        public override void Down()
        {
        }
    }
}
